package gt.proyecto.dbaccess;
// Generated 11/09/2017 10:38:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TblUsuarios generated by hbm2java
 */
public class TblUsuarios  implements java.io.Serializable {


     private BigDecimal idusuario;
     private String usuario;
     private String nombrecompleto;
     private String claveacceso;

    public TblUsuarios() {
    }

	
    public TblUsuarios(BigDecimal idusuario) {
        this.idusuario = idusuario;
    }
    public TblUsuarios(BigDecimal idusuario, String usuario, String nombrecompleto, String claveacceso) {
       this.idusuario = idusuario;
       this.usuario = usuario;
       this.nombrecompleto = nombrecompleto;
       this.claveacceso = claveacceso;
    }
   
    public BigDecimal getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(BigDecimal idusuario) {
        this.idusuario = idusuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getNombrecompleto() {
        return this.nombrecompleto;
    }
    
    public void setNombrecompleto(String nombrecompleto) {
        this.nombrecompleto = nombrecompleto;
    }
    public String getClaveacceso() {
        return this.claveacceso;
    }
    
    public void setClaveacceso(String claveacceso) {
        this.claveacceso = claveacceso;
    }




}


